sudo: false

language: ruby
rvm:
  - 2.5.1,
env:
  global:
    - BROWSER=chrome
  matrix:
    - DB=postgres TEST_SUITE=rubocop
    - DB=postgres TEST_SUITE="rake spec:features"
    - DB=postgres TEST_SUITE="rake spec:models"
    - DB=postgres TEST_SUITE="rake spec:controllers spec:lib spec:routing spec:mailers"
    - DB=postgres TEST_SUITE="rake spec:views spec:helpers"
    - DB=mysql TEST_SUITE="rake spec:models"
    - DB=sqlite TEST_SUITE="rake spec:models"

addons:
  chrome: stable

bundler_args: --path=vendor/bundle --without heroku

cache: bundler

before_script:
  # gem update --system is a workaround for travis-ci/travis-ci#8978
  -sh -c cd Book_V_0.1
  - "gem update --system"
  - sh -c "cp config/database.$DB.yml config/database.yml"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database fat_free_crm_test;' -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -e 'create database fat_free_crm_test;'; fi"
  - "RAILS_ENV=test bundle exec rake spec:preparedb"

# Run specs
script:
  - "RAILS_ENV=test bundle exec $TEST_SUITE"

dist: xenial
services:
  - xvfb
  - postgresql
  - mysql
