# config/app.yml for rails-settings-cached
defaults: &defaults
  foo: "Foo"
  bar: 123
  company_name: "My Company"
  Setting.company_name = 'supersecret'
  GlobalSettings.company_name="Company1"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
