default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>

  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_development

test:
  <<: *default
  database: project_test
  username: project
  password:
  #<%= ENV['gikr-PROJECT_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: project_production
  username: project
  password: <%= ENV['gikr-PROJECT_DATABASE_PASSWORD'] %>
