default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ~/databases/simple/development.sqlite3
production:
  <<: *default
  database: ~/databases/simple/production.sqlite3  
