# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

 #See `secrets.yml` for tips on generating suitable keys.
# production:
#  external_api_key: 1466aac22e6a869134be3d09b9e89232fc2c2289



# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14cbb7dfcacaee41de20e8aa521544bfd33b396072f41e800a1463406feec39ccf23d4d406cbccf772719b8236dbb0020733fb3bcb1ef371eed0fb8e8d6f1bde
  #secret_key_base: 283a68a1f5450db75b9a08618bbcc5e8b332d485fc09a07198380ac4adbd75a0bee2b9876ac01b7349cc56fe94c9c370976ac871abd9a60f65ffff3bc15583bb

test:
  secret_key_base: e8d9db8a05c7a250b812e59d42501a6ef6c0b7affd6252d2eb9ae13fb72ba7180509f5687a886872ac8b1d16ac580abcb642293481f4c2444481a8961571bd9d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
